---
title: "Dataviz for Scientists"
format:
  html:
    theme: [default, style/fonts-landing.scss, style/custom-landing.scss]
author: "[Otho Mantegazza](https://othomantegazza.com/)"

---

<span style="background-color: yellow;">Work in progress!</span>

Slides for the data visualization part of the [2023 Hackathon Workshop on Computational Modeling](https://innovateaihealthlab.co.ke/events/) at the University of Embu, Kenya.

# Slides

## Day 1

1. [Instant Knowledge](200-instant-data.html)
2. [Quick history of Dataviz](210-history.html)
3. [The Grammar of Graphics](220-gg.html)
4. [Exploratory Data Analysis](230-eda.html)

## Day 2

5. [Better Graphs - Part I](310-better-graphs.html)
6. [Better Graphs - Part II](320-better-graphs-2.html)

# Resources

Besides the slides, you can consult any of these [open access books](https://othomantegazza.com/textbook-library) on the topics of data analysis, statistics, programming and data visualization.

# License

This work is licensed by Otho Mantegazza under the [CC BY-NC-SA 4.0 license](https://creativecommons.org/licenses/by-nc-sa/4.0/legalcode). For more information about the non-original bits and pieces, please check the file [LICENSE](https://github.com/othomantegazza/dataviz-for-scientists-slides-python/blob/main/LICENSE) on this course's [Github repo](https://github.com/othomantegazza/dataviz-for-scientists-slides-python).

# Acknowledgements

Big thanks to [Giorgia Ditano](https://giorgia-dit.github.io/about/) for the help and support in reviewing the course material.
